import initScroll from './modules/scroll-suave.js';
import initScrollAnimation from './modules/scroll-animacao.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tab-nav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initHorario from './modules/horario.js';
import initFetchAnimais from './modules/fetchanimais.js';
import initBtcFetch from './modules/btc-fetch.js';

initTabNav();
initAccordion();
initScrollAnimation();
initScroll();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initHorario();
initFetchAnimais();
initBtcFetch();
